on:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v1.1
      with:
        token: ${{ secrets.TOKEN }}
        includeForks: true
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Updated README.md $(date +'at %l:%M %p on %v')"
        git push
        fi

