on:
  schedule:
    - cron: '1 * * * *'
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: macos-latest
    steps:
    - name: Get current time
      uses: josStorer/get-current-time@v2.0.1
      id: current-time
      with:
        format: YYYYMMDD-HH
        utcOffset: "+08:00"

    - name: Use current time
      env:
        TIME: "${{ steps.current-time.outputs.time }}"
        R_TIME: "${{ steps.current-time.outputs.readableTime }}"
        F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        YEAR: "${{ steps.current-time.outputs.year }}"
        DAY: "${{ steps.current-time.outputs.day }}"
      run: echo $TIME $R_TIME $F_TIME $YEAR $DAY

    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "who_am_i.md"
        FILE_DATA: $("echo #For now ($F_TIME) I am Daniel Pustotin\n##@heartsker\n##daniel.pustotin@gmail.com")
        
    - name: Updated who_am_i.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name heartsker
        git config user.email heartsker@gmail.com
        git add .
        git commit -m "Updated who_am_i.md $(date +'at %l:%M %p on %v')"
        git push
        fi
